### ISSUE TITLE
get-argb-pixels not enforcing contract causing segfault

### ISSUE THREAD

**Issue by LeifAndersen** [racket/draw#10]
@bennn and I have the following code that causes a segfault:

```
#lang racket/base

(require pict
         racket/class
         redex/reduction-semantics
         redex/pict)

(define-language nats
  [nat Z])

(define p (term->pict nats (term Z)))
(define b (pict->bitmap p))
(define w (pict-width p)) ; 105.7587890625 should be 106
(define h (pict-height p)) ; 14.2802734375 should be 15
(define pixbuf (make-bytes (* 4 (inexact->exact (ceiling (* w h))))))
(send b get-argb-pixels 0 0 w h pixbuf)
pixbuf
```

Looking at this, `w` and `h` are obviously wrong, and we should have gotten them with `get-width` and `get-hight` on the bitmap directly rather than getting them from the pict.

However, because we are passing non exact-nonnegative-integer? we would expect a contract violation, especially given the contract for the `get-argb-pixels` method:

```
    (get-argb-pixels (->*m
                       (exact-nonnegative-integer?
                        exact-nonnegative-integer?
                        exact-nonnegative-integer?
                        exact-nonnegative-integer?
                        (and/c bytes? (not/c immutable?)))
                       (any/c any/c #:unscaled? any/c)
                       void?))
```

However, what happens is we get a segfault.

Furthermore, if we pass in another incorrect value, say w=0.5 and h=0.5, rather than getting a segault, we just get a buffer filled with some data.

**Comment by LeifAndersen** [comment]
We have a simpler example:

```
#lang racket/base

(require pict racket/class)

(define p (circle 10))
(define b (pict->bitmap p))
(define pixbuf (make-bytes 1000))
(send b get-argb-pixels 0 0 1.1 1.1 pixbuf)
pixbuf
```

**Comment by mflatt** [comment]
It looks like checks were removed in 9f3281596a996c9a7ff6159b7da9c6cc362b491a, but functions like `make-bitmap` were not given a contract. I think the repair is not entirely trivial, because a contract on `make-bitmap` needs an object contract that has the same information as the `bitmap%/c` class contract. Or we could restore the original checks.

**Comment by mfelleisen** [comment]
@mflatt When Asumu removed these checks, he did so after adding contracts. Indeed, now that I checked, the commit comment says “there are contracts.” I don’t understand your reply in this context.

**Comment by mflatt** [comment]
I was overlooking `instanceof/c`, which is what I needed to write a contract for `make-bitmap` in terms of `bitmap%/c`.

**Comment by mflatt** [comment]
@mfelleisen It turns out that some contracts were missing.

**Comment by mfelleisen** [comment]
@mflatt I can’t find the relevant contracts.

**Comment by mflatt** [comment]
The contracts are imposed (or should be) in "draw/draw-lib/racket/draw.rkt".

I'll push a repair to add contracts tomorrow, after testing more. As far as I can tell, the `provide`s that need contracts are `make-bitmap`, make-platform-bitmap`, `make-monochrome-bitmap`, `read-bitmap`, `the-pen-list`, and `the-brush-list`.

**Comment by rfindler** [comment]
FWIW, the contracts work best if they are imposed in the library that is
actually required (so racket/draw in this case?). (Of course, if the
positive positions never fail (which seems likely here) then it doesn't
matter.)

**Comment by LeifAndersen** [comment]
Woot, thank you for fixing this. I suspected that the bitmap object created by `pict->bitmap` wasn't getting a wrapper, but couldn't find out where (as it seemed to...) So thank you.
