### ISSUE TITLE
Pango AppKit workaround for CS and/or Aarch64?

### ISSUE THREAD

**Issue by LiberalArtist** [racket/draw#33]
There is a workaround here to prevent a problem with Pango's Core Text backed by loading AppKit, but it is specific to `"x86_64-macosx/3m"`:

https://github.com/racket/draw/blob/253dbf895966fd8179d4b8c3620c60190647cfd0/draw-lib/racket/draw/unsafe/pango.rkt#L49-L55

Perhaps it should use `(system-type 'os)` or `'os*` to also apply to, say, `"aarch64-macosx/cs"`? Or maybe the underlying problem has been fixed?

**Comment by mflatt** [comment]
I think the underlying problem must have been fixed, so I'll remove this in the near future.
